version: '3'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      backend:
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=your@gmail.com
      - CF_DNS_API_TOKEN=your-api-key
      # - CF_API_KEY=YOU_API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/docker-basement/mydir/traefik/config/traefik.yml:/traefik.yml:ro
      - /root/docker-basement/mydir/traefik/config/config.yml:/config.yml:ro
      - /root/docker-basement/mydir/traefik/ssl-certs/acme.json:/acme.json
      - /root/docker-basement/mydir/traefik/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.eu.org`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=YOUR_USERNAME_PASSWORD"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.yourdomain.eu.org`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=yourdomain.eu.org"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.yourdomain.eu.org"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  backend:
    name: backend
    external: true