global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

# -- (Optional) Disable TLS Cert verification check
serversTransport:
  insecureSkipVerify: true

# -- (Optional) Overwrite Default Certificates
#tls:
#  stores:
#    default:
#      defaultCertificate:
#        certFile: /etc/traefik/certs/cert.pem
#        keyFile: /etc/traefik/certs/cert-key.pem
# -- (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

certificatesResolvers:
  cloudflare:
    acme:
      email: rizalaliakbar.business@gmail.com
      storage: /ssl-certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      #httpChallenge:
      #  entryPoint: web
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    # -- (Optional) Enable this, if you want to expose all containers autom>
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true