version: '3'
#volumes:
#  ztncui:
#  zt1:
services:
  ztncui:
    image: keynetworks/ztncui
    container_name: ztncui
    ports:
      #- 3443:3443 #dashboard port
      - 3180:3180
    environment:
      - USER_UID=998 #adjust to your system
      - USER_GID=100 #adjust to your system
      - NODE_ENV=production
      - HTTPS_PORT=3443
      - ZTNCUI_PASSWD=password  #change this
      - MYDOMAIN=zt.zilnet.eu.org #change this to the domain you want to use for the controller
      - MYADDR=12.34.56.78 #this is optional. if you use it, this is the public IP your ISP gave you
    volumes:
      - ztncui:/opt/key-networks/ztncui/etc
      - zt1:/var/lib/zerotier-one
    networks:
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.entrypoints=web'
      - 'traefik.http.routers.portainer.rule=Host(`zt.zilnet.eu.org`)'
      - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.ssl-header.headers.customrequestheaders.X-Forwarded-Proto=https'
      - 'traefik.http.routers.portainer.middlewares=https-redirect'
      - 'traefik.http.routers.portainer-secure.entrypoints=websecure'
      - 'traefik.http.routers.portainer-secure.rule=Host(`zt.zilnet.eu.org`)'
      - 'traefik.http.services.portainer.loadbalancer.server.port=3443'
      - 'traefik.http.routers.portainer-secure.service=ztncui'
      - 'traefik.http.routers.portainer-secure.tls=true'