version: '3'

services:
  mikhmon:
    container_name: mikhmon
    restart: always
    image: naufkia/mikhmonv3
    #volumes:
      #- /etc/localtime:/etc/localtime
      #- /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    ports:
      - "8181:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mikhmon.rule=Host(`mikhmon.zilnet.eu.org`)"
      - "traefik.http.routers.mikhmon.entrypoints=websecure"
      - "traefik.docker.network=backend"

#volumes:
#  mikhmon-data:
#    driver: local
#    name: mikhmon-data

networks:
  backend:
    external: true