version: '3'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/config:/etc/traefik
      - traefik-ssl-certs:/ssl-certs
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    environment:
      - "CF_API_EMAIL=${CF_API_EMAIL}"
      - "CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}"
      # - CF_API_KEY=YOU_API_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.zilnet.eu.org`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.zilnet.eu.org`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=zilnet.eu.org"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.zilnet.eu.org"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    restart: always
    networks:
      frontend:

volumes:
  traefik-ssl-certs:
    driver: local
    name: traefik-ssl-certs

networks:
  frontend:
    external: true